# Generated by Django 3.1.4 on 2020-12-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=100)),
                ('size', models.FloatField()),
                ('date_open', models.DateTimeField(verbose_name='contract start date')),
                ('date_close', models.DateTimeField(verbose_name='contract expiry date')),
                ('status', models.CharField(max_length=100)),
                ('result', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timedcontracts.market')),
            ],
        ),
    ]
