# Generated by Django 3.1.4 on 2020-12-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timedcontracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_close',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_open',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='result',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='ticker',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
