# Generated by Django 3.1.4 on 2020-12-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timedcontracts', '0002_auto_20201204_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('LONG', 'SHORT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(default='OPEN', max_length=100),
        ),
    ]
